services:

  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    container_name: smart-parking-backend
    ports:
      - "8000:8000"
    environment:
      JWT_SECRET: ${JWT_SECRET}
      ADMIN_PASSWORD: ${ADMIN_PASSWORD}
      FRONTEND_URL: ${FRONTEND_URL}
    volumes:
      - parking_database:/app/database
    restart: unless-stopped

  frontend:
    build:
      context: .
      dockerfile: frontend/Dockerfile
    container_name: smart-parking-frontend
    ports:
      - "5173:80"
    depends_on:
      - backend
    restart: unless-stopped

volumes:
  parking_database: